CREATE TABLE KAYTTAJA (
KAYTTAJATUNNUS varchar(255) not null PRIMARY KEY,
SALASANA varchar(255),
NIMI varchar(255) not null,
ROOLI integer not null
);

CREATE TABLE PROJEKTI (
PROJEKTIN_NIMI varchar(255) not null PRIMARY KEY,
TYOTUNTIBUDJETTI float(4),
ALKAMISPAIVAMAARA date,
LOPPUMISPAIVAMAARA date
);

CREATE TABLE KAYTTAJAN_PROJEKTIT (
PROJEKTIN_NIMI varchar(255) not null,
KAYTTAJATUNNUS varchar(255) not null,
CONSTRAINT pk_kayttajan_projektit PRIMARY KEY (KAYTTAJATUNNUS,PROJEKTIN_NIMI),
CONSTRAINT fk_kayttajatunnus FOREIGN KEY (KAYTTAJATUNNUS) REFERENCES KAYTTAJA (KAYTTAJATUNNUS),
CONSTRAINT fk_projekti FOREIGN KEY (PROJEKTIN_NIMI) REFERENCES PROJEKTI (PROJEKTIN_NIMI)
);

CREATE TABLE TYOTEHTAVA (
TYOTEHTAVAN_NIMI varchar(255) not null,
BUDJETOIDUT_TYOTUNNIT float(4),
PROJEKTIN_NIMI varchar(255) not null,
CONSTRAINT pk_tyotehtava PRIMARY KEY (TYOTEHTAVAN_NIMI,PROJEKTIN_NIMI),
CONSTRAINT fk_projekti FOREIGN KEY (PROJEKTIN_NIMI) REFERENCES PROJEKTI (PROJEKTIN_NIMI)
);

CREATE TABLE KIRJAUS (
PAIVAMAARA date not null,
TEHDYT_TYOTUNNIT float(4) not null,
SELITYS varchar(1000),
KAYTTAJATUNNUS varchar(255) not null,
PROJEKTIN_NIMI varchar(255) not null,
TYOTEHTAVAN_NIMI varchar(255) not null,
CONSTRAINT pk_kirjaus PRIMARY KEY (KAYTTAJATUNNUS,TYOTEHTAVAN_NIMI,PROJEKTIN_NIMI,PAIVAMAARA),
CONSTRAINT fk_kayttajatunnus FOREIGN KEY (KAYTTAJATUNNUS) REFERENCES KAYTTAJA (KAYTTAJATUNNUS),
CONSTRAINT fk_tyotehtava FOREIGN KEY (TYOTEHTAVAN_NIMI,PROJEKTIN_NIMI) REFERENCES TYOTEHTAVA (TYOTEHTAVAN_NIMI,PROJEKTIN_NIMI)
);