CREATE TABLE KAYTTAJA (
KAYTTAJATUNNUS varchar(255) not null PRIMARY KEY,
SALASANA varchar(255),
NIMI varchar(255) not null,
ROOLI integer NOT NULL
);

CREATE TABLE PROJEKTI (
PROJEKTIN_NIMI varchar(255) not null PRIMARY KEY,
TYOTUNTIBUDJETTI float(4),
ALKAMISPAIVAMAARA date,
LOPPUMISPAIVAMAARA date
);

CREATE TABLE TYOTEHTAVA (
TYOTEHTAVAN_NIMI varchar(255) not null PRIMARY KEY,
BUDJETOIDUT_TYOTUNNIT float(4),
PROJEKTIN_NIMI varchar(255),
CONSTRAINT fk_projekti FOREIGN KEY (PROJEKTIN_NIMI) REFERENCES PROJEKTI (PROJEKTIN_NIMI)
);

CREATE TABLE KIRJAUS (
ID bigint not null PRIMARY KEY,
PAIVAMAARA date not null,
SELITYS varchar(500),
TEHDYT_TYOTUNNIT float(4) not null,
KAYTTAJATUNNUS varchar(255),
PROJEKTIN_NIMI varchar(255),
TYOTEHTAVAN_NIMI varchar(255),
CONSTRAINT fk_kayttajatunnus FOREIGN KEY (KAYTTAJATUNNUS) REFERENCES KAYTTAJA (KAYTTAJATUNNUS),
CONSTRAINT fk_projekti FOREIGN KEY (PROJEKTIN_NIMI) REFERENCES PROJEKTI (PROJEKTIN_NIMI),
CONSTRAINT fk_tyotehtava FOREIGN KEY (TYOTEHTAVAN_NIMI) REFERENCES TYOTEHTAVA (TYOTEHTAVAN_NIMI)
);